[project]
name = "finances-file-service"
version = "0.1.0"
description = ""
authors = [
    {name = "Mate Csornyei",email = "mcsornyei@priogen.nl"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard] (>=0.115.12,<0.116.0)"
]

[tool.poetry]
packages = [{include = "finances_file_service", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
