name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Install Poetry
      - name: Install Poetry
        run: pip install poetry==2.1.2

      # Step 4: Install dependencies
      - name: Install dependencies
        run: poetry install --no-root

      # Step 5: Set PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      # Step 6: Run linters (ruff, isort, black)
      - name: Run ruff
        run: poetry run ruff check .

      - name: Run isort
        run: poetry run isort --check-only .

      - name: Run black
        run: poetry run black --check .

      # Step 7: Run tests
      - name: Run tests
        run: poetry run pytest

      # Step 8: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 9: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/finances-file-service:latest .
          docker push ghcr.io/${{ github.repository_owner }}/finances-file-service:latest
